server:
  port: 8083
security:
  oauth2:
    client:
      client-id: beo-app-client
      client-secret: e6aec4e0-e421-415a-8f84-d06237963831
logging:
  level:
    root: INFO
#    org:
#      springframework:
#        security: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: beo
    password: beo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  liquibase:
#    change-log: classpath:db/changelog/changelog.yml