server:
  port: 8080
security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE