server:
  port: 8080
security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: beo
    password: beo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  liquibase:
#    change-log: classpath:db/changelog/changelog.yml